Loop if admin port is not open after restart. Don't use default JBOSS_HOME. exit 1 if sh-script fails.

diff --git a/bin/jboss7 b/bin/jboss7
--- a/bin/jboss7
+++ b/bin/jboss7
@@ -25,8 +25,8 @@ TIMEOUT=40
 test -f $HOME/.${instanzName}rc && . $HOME/.${instanzName}rc
 
 if [ X$JBOSS_HOME = X ]; then
-	echo "WARNING! Variable JBOSS_HOME is not set. Using Default value $HOME/jboss!"
-	JBOSS_HOME=$HOME/jboss
+ 	echo "ERROR: Variable JBOSS_HOME is not set."
+ 	exit 1
 fi
 
 TIMEOUT=${JBOSS_TIMEOUT:-"$TIMEOUT"}
@@ -129,7 +129,7 @@ configure() {
   	  sh)
 		echo /bin/sh $file
 		/bin/sh $file || {
-			echo "[ERROR]: failed executing /bin/sh $file" ; exit 0
+			echo "[ERROR]: failed executing /bin/sh $file" ; exit 1
 		}
   	  ;;
   	  module)
@@ -182,6 +182,30 @@ check_started() {
 	egrep -iq 'JBoss (EAP|AS).*(started|gestartet)' $file
 }
 
+###########################
+# check whether admin application is available
+###########################
+check_admin_app() {
+    $admin -c pwd > /dev/null 2>&1
+}
+
+###########################
+# wait until admin port is available
+###########################
+wait_for_admin_app() {
+    cnt=0
+    while [ ${cnt} -le 30 ]; do
+		check_admin_app && return 0
+        let cnt=${cnt}+1
+        echo "INFO: [$(date +'%Y-%m-%d %H:%M:%S')] Admin application not available at port ${ADMIN_PORT}" 
+        sleep 1
+    done
+    echo "ERROR: Admin application not available at port ${ADMIN_PORT}" 
+	exit 1
+}
+
+
+
 ################################################
 #                   MAIN
 ################################################
@@ -214,7 +238,7 @@ case "$action" in
     echo 
     if is_running; then
 		if check_started $out; then
-			sleep 2 # Workaround. It seems that sometimes the admin-port is not open immediately
+			wait_for_admin_app  ### It seems that sometimes the admin-port is not open immediately ###
     		echo "$displayName started"
 		else
 			echo "$displayName process seems to run, but no 'started' message was found in output within $START_TIMEOUT seconds." 1>&2
@@ -258,8 +282,14 @@ case "$action" in
     if [ -z "$pid" ]; then
         #not running
         echo "$displayName is not running"
+		echo "  Admin-Port: $ADMIN_PORT"
     else
         echo "$displayName running on pid $pid"
+		if check_admin_app; then
+			echo "  Admin-Port: $ADMIN_PORT open"
+		else
+			echo "  Admin-Port: $ADMIN_PORT not reachable!"
+		fi
     fi
     echo "  JBOSS_HOME=$JBOSS_HOME"
 	if [ ! -d $JBOSS_HOME ]; then
